/*
 * This source file was generated by the Gradle 'init' task
 */
package org.run;

import org.test.BubbleSortTest;
import org.test.InsertionSortTest;
import org.test.MergeSortTest;
import org.test.QuickSortTest;
import org.test.SelectionSortTest;
import org.test.search.BinarySearchTest;

public class App 
{
    public static void main(String[] args) 
    {
        // BubbleSortTest.exec();
        // InsertionSortTest.exec();
        // SelectionSortTest.exec();
        // MergeSortTest.exec();
        // QuickSortTest.exec();
        BinarySearchTest.exec();
    }
}
