/*
 * This source file was generated by the Gradle 'init' task
 */
package org.run;

import org.test.BubbleSortTest;

public class App 
{
    
    public static void main(String[] args) 
    {
        BubbleSortTest.exec();
    }
}
