/*
 * This source file was generated by the Gradle 'init' task
 */
package org.run;

import org.test.BubbleSortTest;
import org.test.InsertionSortTest;

public class App 
{
    public static void main(String[] args) 
    {
        // BubbleSortTest.exec();
        InsertionSortTest.exec();
    }
}
